# Generated by Django 5.1.7 on 2026-04-04 03:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(blank=True, max_length=40)),
                ('celular', models.CharField(blank=True, max_length=30)),
                ('cargo', models.CharField(blank=True, max_length=120)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('fecha_contratacion', models.DateField(default=django.utils.timezone.localdate)),
                ('foto_base64', models.TextField(blank=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de usuario',
                'verbose_name_plural': 'Perfiles de usuario',
            },
        ),
    ]
