# Generated by Django 5.1.7 on 2026-04-29 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalificacionProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calidad_suministro', models.IntegerField(choices=[(1, 'Muy Bajo'), (2, 'Bajo'), (3, 'Regular'), (4, 'Bueno'), (5, 'Excelente')])),
                ('cumplimiento_tiempos', models.IntegerField(choices=[(1, 'Muy Bajo'), (2, 'Bajo'), (3, 'Regular'), (4, 'Bueno'), (5, 'Excelente')])),
                ('precio_calidad', models.IntegerField(choices=[(1, 'Muy Bajo'), (2, 'Bajo'), (3, 'Regular'), (4, 'Bueno'), (5, 'Excelente')])),
                ('comentario', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='suppliers.proveedor')),
            ],
            options={
                'ordering': ('-creado_en',),
            },
        ),
    ]
