# Generated by Django 5.1.7 on 2026-05-09 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_calificacionproveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='productos_suministrados',
            field=models.TextField(blank=True, help_text='Descripción de materias primas o productos que suministra (una por línea o separados por coma).'),
        ),
    ]
