# Generated by Django 5.1.7 on 2026-04-28 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pasillo', models.CharField(max_length=20)),
                ('estante', models.CharField(max_length=20)),
                ('seccion', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ('pasillo', 'estante', 'seccion'),
                'unique_together': {('pasillo', 'estante', 'seccion')},
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='inventory.ubicacion'),
        ),
    ]
