# Generated by Django 5.1

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0002_add_ubicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='registrado_por',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='movimientos_inventario',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
