# Generated by Django 5.1.7 on 2026-05-09 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_movimientoinventario_registrado_por'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroEliminacionProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_id_original', models.PositiveIntegerField()),
                ('codigo', models.CharField(max_length=40)),
                ('nombre', models.CharField(max_length=160)),
                ('categoria', models.CharField(max_length=120)),
                ('cantidad_al_eliminar', models.IntegerField()),
                ('eliminado_en', models.DateTimeField(auto_now_add=True)),
                ('eliminado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_eliminaciones_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-eliminado_en',),
            },
        ),
    ]
