# Generated by Django 5.1.7 on 2026-05-09 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0004_hu_pdf_gaps'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResolucionAlerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_nombre', models.CharField(max_length=160)),
                ('tipo_alerta', models.CharField(choices=[('low-stock', 'Stock bajo'), ('expiration', 'Proximo a vencer'), ('expired', 'Vencido')], max_length=20)),
                ('accion', models.CharField(choices=[('reabastecer', 'Reabastecer'), ('extender', 'Extender vigencia'), ('descartar', 'Descartar'), ('manual', 'Marcada como atendida')], max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resoluciones_alerta', to='inventory.producto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_resueltas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-creado_en',),
            },
        ),
    ]
